apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: message-dumper-github-subscription
  namespace: default
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: githubchannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: message-dumper
